name: vps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y screen

      - name: Generate multiple SSHX links
        run: |
          mkdir -p output
          > output/sshx_links.txt

          for i in {1..3}; do
            screen -dmS sshx_$i bash -c 'curl -sSf https://sshx.io/get | sh -s run | tee -a output/sshx_links.txt'
            sleep 5
          done

          sleep 20  # Tunggu semua sesi selesai
          cat output/sshx_links.txt

      - name: Commit SSHX links
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add output/sshx_links.txt
          git commit -m "Add generated SSHX links"
          git push
